branch-defaults:
  master:
    environment: Sharing-blog-env
environment-defaults:
  Sharing-blog-env:
    branch: null
    repository: null
global:
  application_name: sharing-blog
  default_ec2_keyname: sharing-blog
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
deploy:
  artifact: target/sharingblog-0.0.1-SNAPSHOT.jar